name = "MexicoCityMetro"
uuid = "4bb9ba41-7e71-4b14-85d7-16d2b93b1b6f"
authors = ["Luis Eduardo Ramírez Montoya <luiseduardoramirezmontoya@ciencias.unam.mx> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
